contact_links:
  - name: Blank issue
    url: https://github.com/huggingface/diffusers/issues/new
    about: Other
  - name: Forum
    url: https://discuss.huggingface.co/
    about: General usage questions and community discussions