Collections:
- Name: SAR
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adam
    Training Resources: 8x NVIDIA A100-SXM4-80GB
    Epochs: 5
    Batch Size: 3072
    Architecture:
      - ResNet31OCR
      - SAREncoder
      - ParallelSARDecoder
  Paper:
    URL: https://arxiv.org/pdf/1811.00751.pdf
    Title: 'Show, Attend and Read:A Simple and Strong Baseline for Irregular Text Recognition'
  README: configs/textrecog/sar/README.md

Models:
  - Name: sar_resnet31_parallel-decoder_5e_st-sub_mj-sub_sa_real
    Alias: SAR
    In Collection: SAR
    Config: configs/textrecog/sar/sar_resnet31_parallel-decoder_5e_st-sub_mj-sub_sa_real.py
    Metadata:
      Training Data:
        - ICDAR2011
        - ICDAR2013
        - ICDAR2015
        - COCO text
        - IIIT5K
        - SynthText
        - SynthAdd
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.9533
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8841
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.9369
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.7602
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.8326
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.9028
    Weights: https://download.openmmlab.com/mmocr/textrecog/sar/sar_resnet31_parallel-decoder_5e_st-sub_mj-sub_sa_real/sar_resnet31_parallel-decoder_5e_st-sub_mj-sub_sa_real_20220915_171910-04eb4e75.pth

  - Name: sar_resnet31_sequential-decoder_5e_st-sub_mj-sub_sa_real
    In Collection: SAR
    Config: configs/textrecog/sar/sar_resnet31_sequential-decoder_5e_st-sub_mj-sub_sa_real.py
    Metadata:
      Training Data:
        - ICDAR2011
        - ICDAR2013
        - ICDAR2015
        - COCO text
        - IIIT5K
        - SynthText
        - SynthAdd
        - Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.9553
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8717
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.9409
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.7737
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.8093
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.8924
    Weights: https://download.openmmlab.com/mmocr/textrecog/sar/sar_resnet31_sequential-decoder_5e_st-sub_mj-sub_sa_real/sar_resnet31_sequential-decoder_5e_st-sub_mj-sub_sa_real_20220915_185451-1fd6b1fc.pth
