Collections:
- Name: CRNN
  Metadata:
    Training Data: OCRDataset
    Training Techniques:
      - Adadelta
    Epochs: 5
    Batch Size: 64
    Training Resources: 1x NVIDIA A100-SXM4-80GB
    Architecture:
      - MiniVGG
      - CRNNDecoder
  Paper:
    URL: https://arxiv.org/pdf/1507.05717.pdf
    Title: 'An End-to-End Trainable Neural Network for Image-based Sequence Recognition and Its Application to Scene Text Recognition'
  README: configs/textrecog/crnn/README.md

Models:
  - Name: crnn_mini-vgg_5e_mj
    Alias: CRNN
    In Collection: CRNN
    Config: configs/textrecog/crnn/crnn_mini-vgg_5e_mj.py
    Metadata:
      Training Data: Syn90k
    Results:
      - Task: Text Recognition
        Dataset: IIIT5K
        Metrics:
          word_acc: 0.8053
      - Task: Text Recognition
        Dataset: SVT
        Metrics:
          word_acc: 0.8053
      - Task: Text Recognition
        Dataset: ICDAR2013
        Metrics:
          word_acc: 0.8739
      - Task: Text Recognition
        Dataset: ICDAR2015
        Metrics:
          word_acc: 0.5556
      - Task: Text Recognition
        Dataset: SVTP
        Metrics:
          word_acc: 0.6093
      - Task: Text Recognition
        Dataset: CT80
        Metrics:
          word_acc: 0.5694
    Weights: https://download.openmmlab.com/mmocr/textrecog/crnn/crnn_mini-vgg_5e_mj/crnn_mini-vgg_5e_mj_20220826_224120-8afbedbb.pth
