Collections:
- Name: DRRG
  Metadata:
    Training Data: SCUT-CTW1500
    Training Techniques:
      - SGD with Momentum
    Training Resources: 4x NVIDIA A100-SXM4-80GB
    Architecture:
      - ResNet
      - FPN_UNet
  Paper:
    URL: https://arxiv.org/abs/2003.07493.pdf
    Title: 'Deep Relational Reasoning Graph Network for Arbitrary Shape Text Detection'
  README: configs/textdet/drrg/README.md

Models:
  - Name: drrg_resnet50_fpn-unet_1200e_ctw1500
    Alias: DRRG
    In Collection: DRRG
    Config: configs/textdet/drrg/drrg_resnet50_fpn-unet_1200e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou: 0.8467
    Weights: https://download.openmmlab.com/mmocr/textdet/drrg/drrg_resnet50_fpn-unet_1200e_ctw1500/drrg_resnet50_fpn-unet_1200e_ctw1500_20220827_105233-d5c702dd.pth

  - Name: drrg_resnet50-oclip_fpn-unet_1200e_ctw1500
    In Collection: DRRG
    Config: configs/textdet/drrg/drrg_resnet50-oclip_fpn-unet_1200e_ctw1500.py
    Metadata:
      Training Data: CTW1500
    Results:
      - Task: Text Detection
        Dataset: CTW1500
        Metrics:
          hmean-iou:
    Weights:
